name: Run server

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run server
      run: npm install express
      run: node server.js
